apiVersion : apps/v1
kind : Deployment
metadata :
  name : nginx-deploy
  labels :
    name : nginx-deploy
spec :
  replicas : 3
  selector :
    matchLabels :
      name : nginx
  template :
    metadata :
      labels :
        name : nginx
    spec :
      containers :
        - image : nginx
          name : nginx
